---
title: "Introduction Draft"
author: "Janetta E. Skarp"
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: margin=2cm
fonsize: 11pt
output: 
  pdf_document:
    latex_engine: xelatex
sansfont: Calibri Light
urlcolor: blue
header-includes:
   - \setlength\parindent{24pt}
   - \usepackage{setspace}\doublespacing
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

When modelling infectious disease outbreaks, the disease's effective reproduction number, often denoted as $R$, is of particular interest. $R$ refers to the number of susceptible individuals that an infectious individual infects on average. In other words, it is a measure of the disease's transmissibility. Due to this, $R$ can be used as an indicator for whether or not the disease's transmission is increasing or decreasing at a given timepoint. 

$R$ is correlated with disease incidence. Disease incidence is defined as the number of new cases for a given time period. If $R$ is above 1, on average more than one susceptible individual is being infected by each infected individual and thus the number of cases is increasing. If $R$ is below 1, each infected individual infects fewer than one person on average, implying that the number of cases is on the decline. Whether or not the number of cases in an ongoing outbreak is increasing or decreasing is critical information for those in charge of planning outbreak response. If the number of cases is increasing, it can suggest for example that more beds may be needed in hospitals, allowing hospitals to take the necessary precautions. If the number of cases is reducing, additional care may be put into ensuring that the current outbreak response strategies are maintained until the end of the outbreak.       

Many methods have been developed for inferring $R$ from data. $R$ can be calculated in a parametric or non-parametric manner. Parametric methods include approaches such as branching process and compartmental models, while epidemic trees represent a non-parametric approach (Wallinga \& Teunis 2004; Ferrari et al. 2005; Haydon et al. 2003). These inferential methods would be unlikely to result in exactly the same estimated value of $R$ if given the same data. One study compared multiple different models, an exponential growth rate model, two types of SEIR model, and a stochastic SIR model on the same Spanish flu outbreak data and found that while there were differences in the R estimates, all of them fell within an acceptable range (Chowell et al. 2007). Altering one's assumptions while keeping the model otherwise unchanged can also result in differing estimates. For example, assumptions regarding contact patterns between individuals affected the R estimate for H1N1 though all estimates were found to be within an acceptable range (Chowell et al. 2007; Ajelli et al. 2014).

Branching process models are now commonly used as an alternative to compartmental models for estimating transmissibility during infectious disease outbreaks. Compartmental models have compartments for every disease category and a defined population size. Branching process models, on the other hand, have an infinite pool of susceptibles and transmissibility is estimated by calculating the likelihood of each susceptible individual being infected by a given infected individual, normalising for the likelihood that that susceptible was infected by another infected individual (Walling \& Teunis 2004). From this estimate of $R$, incidence can be forecasted by also using a branching process model (Nouvellet et al. 2017). Both methods can be and have been used for forecasting disease incidence (Viboud et al. 2017).

The branching process modelling approach can be used to model outbreaks in real-time. Here $R_{t}$, the effective reproduction number for a time window, can be used as the subject of estimation (Wallinga \& Teunis 2004; Cori et al. 2013). Knowledge of the $R_{t}$ of the most recent timepoint can be used for forecasting incidence in the following time period (Nouvellet et al. 2017). Disease incidence forecasts can be used to aid decision-making in outbreak situations. Forecasts suggesting a major increase in the number of cases in the following weeks may highlight a need for additional hospital staff in the near future for example. 

Other incidence forecasting methods exist, but not all methods of estimating incidence perform equally well. In the RAPIDD (Research and Policy for Infectious Disease Dynamics) challenge, different modelling groups were issued with the task of forecasting the incidence of simulated Ebola epidemics and nine different models were compared for the occasion (Viboud et al. 2017). A group utilising the branching process modelling approach was among the strongest approaches, outperforming groups using methods such as compartmental models, logistic growth equations, and agent-based models (Viboud et al. 2017, Nouvellet et al. 2017).

During the Ebola epidemic of 2013-2016, a lack of ready-to-use tools for forecasting epidemics was noted. This led to the development of new tools by groups such as the R Epidemics Consortium (RECON). Since then, various methods for forecasting incidence have been developed. Many of these use tools incorporating branching process models when forecasting. Such modelling tools include the R packages *EpiEstim*, *epitrix*, *earlyR*, and *projections* (a brief description of each package will be given in the Methods). However, branching process model forecasting tools' ability to accurately predict the course of an epidemic in real time has not been evaluated (from project description). It is possible, for instance, that they perform better on specific types of outbreak, such as outbreaks with an exponential growth phase, or with larger outbreaks.

# Aims

In this project, I use publicly available empirical outbreak data for different diseases to assess and compare the performance of currently available incidence forcasting methods provided by RECON. Particular focus is placed on the methods' performance during the early stages of outbreaks. (The impact of factors such as under-reporting, reporting delays, or super-spreading may also be considered.)
